fix: contributors list
CMPUT301W21T05/KrowdTrialz pull request #136
Opened 2021-04-02 20:36 UTC by vasu-gupta01

An alternate getContributors method was created in the Experiments class. The issue seems to be resolved but could use some further testing to verify that the checkboxes are not misbehaving.

2021-04-02 20:56 UTC, arrooney commented on app/src/main/java/com/T05/krowdtrialz/ui/contributors/ContributorsActivity.java
> +    private void updateConList(Experiment exp){
maybe name this `updateContributorList` and add a javadoc comment

2021-04-03 12:56 UTC, vasu-gupta01 commented
@arrooney @Ricky-Au Using a button instead of checkbox seems to fix the issue. Previously, calling setChecked() was triggering the onCheckedListener causing it to misbehave.

2021-04-03 16:03 UTC, arrooney requested changes
Seems to fix the problem -- just a few UI improvements to be made

2021-04-03 16:03 UTC, arrooney commented on app/src/main/java/com/T05/krowdtrialz/ui/contributors/ContributorList.java
> +                    Log.d(TAG, "Ignored User");
Can you also toggle the colour here - both when the button text is first set and in the onclick. I think orange (0xFFFF9800) would be good for whenever the box says "Ignore" and Blue (0xFF3F51B5) whenever the button says "Un-ignore".

2021-04-03 18:04 UTC, Ricky-Au approved these changes

2021-04-03 21:57 UTC, arrooney approved these changes

2021-04-04 03:53 UTC, merged